services:
  - type: web
    name: flask-inventory-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USE_TLS
        value: "true"
      # Set these in Render Dashboard -> Environment
      - key: SMTP_USERNAME
      - key: SMTP_PASSWORD
      - key: EMAIL_SENDER
databases:
  - name: inventory-db
    plan: free
